slogan() :- cls(),
            write(" ___________________________________________________________________________"),nl,
            write("|                                                                           |"),nl,
            write("|      #####    ####  #########  ##        ##  ##  #######  ##       ##     |"),nl,
            write("|      ## ##   ## ##  ##     ##   ##      ##   ##  ##       ##   #   ##     |"),nl,
            write("|      ##  ## ##  ##  ##     ##    ##    ##    ##  #######  ##  ###  ##     |"),nl,
            write("|      ##   ###   ##  ##     ##     ##  ##     ##  ##       ## ## ## ##     |"),nl,
            write("|      ##    #    ##  #########      ####      ##  #######  ####   ####     |"),nl,
            write("|                                                                           |"),nl,
            write("|           UMA PLATAFORMA PARA RECOMENDACAO E AVALIACAO DE FILMES          |"),nl,
            write("|___________________________________________________________________________|"),nl,
            sleep(2).

loading() :- cls(),
             load1(),
             sleep(1),
             cls(),
             load2(),
             sleep(1),
             cls(),
             load3(),
             sleep(1),
             cls().

load1() :- write(" ___________________________________________________________________________"),nl,
           write("|                                                                           |"),nl,
           write("|      #####    ####  #########  ##        ##  ##  #######  ##       ##     |"),nl,
           write("|      ## ##   ## ##  ##     ##   ##      ##   ##  ##       ##   #   ##     |"),nl,
           write("|      ##  ## ##  ##  ##     ##    ##    ##    ##  #######  ##  ###  ##     |"),nl,
           write("|      ##   ###   ##  ##     ##     ##  ##     ##  ##       ## ## ## ##     |"),nl,
           write("|      ##    #    ##  #########      ####      ##  #######  ####   ####     |"),nl,
           write("|                                                                           |"),nl,
           write("|           UMA PLATAFORMA PARA RECOMENDACAO E AVALIACAO DE FILMES          |"),nl,
           write("|                                                                           |"),nl,
           write("|                                   o                                       |"),nl,
           write("|___________________________________________________________________________|"),nl.

load2() :- write(" ___________________________________________________________________________"),nl,
           write("|                                                                           |"),nl,
           write("|      #####    ####  #########  ##        ##  ##  #######  ##       ##     |"),nl,
           write("|      ## ##   ## ##  ##     ##   ##      ##   ##  ##       ##   #   ##     |"),nl,
           write("|      ##  ## ##  ##  ##     ##    ##    ##    ##  #######  ##  ###  ##     |"),nl,
           write("|      ##   ###   ##  ##     ##     ##  ##     ##  ##       ## ## ## ##     |"),nl,
           write("|      ##    #    ##  #########      ####      ##  #######  ####   ####     |"),nl,
           write("|                                                                           |"),nl,
           write("|           UMA PLATAFORMA PARA RECOMENDACAO E AVALIACAO DE FILMES          |"),nl,
           write("|                                                                           |"),nl,
           write("|                                      o                                    |"),nl,
           write("|___________________________________________________________________________|"),nl.

load3() :- write(" ___________________________________________________________________________"),nl,
           write("|                                                                           |"),nl,
           write("|      #####    ####  #########  ##        ##  ##  #######  ##       ##     |"),nl,
           write("|      ## ##   ## ##  ##     ##   ##      ##   ##  ##       ##   #   ##     |"),nl,
           write("|      ##  ## ##  ##  ##     ##    ##    ##    ##  #######  ##  ###  ##     |"),nl,
           write("|      ##   ###   ##  ##     ##     ##  ##     ##  ##       ## ## ## ##     |"),nl,
           write("|      ##    #    ##  #########      ####      ##  #######  ####   ####     |"),nl,
           write("|                                                                           |"),nl,
           write("|           UMA PLATAFORMA PARA RECOMENDACAO E AVALIACAO DE FILMES          |"),nl,
           write("|                                                                           |"),nl,
           write("|                                         o                                 |"),nl,
           write("|___________________________________________________________________________|"),nl.

cls() :- write('\33\[2J').

logOpt() :- write(" ___________________________________________________________________________"),nl,
            write("|                                                                           |"),nl,
            write("|                                ACESSE O SISTEMA                           |"),nl,
            write("|                                                                           |"),nl,
            write("|     1. FAZER LOGIN                                                        |"),nl,
            write("|     2. REALIZAR CADASTRO                                                  |"),nl,
            write("|                                                                           |"),nl,
            write("|     OPCAO:                                                                |"),nl,
            write("|___________________________________________________________________________|"),nl.

menu() :- write(" ___________________________________________________________________________"),nl,
          write("|                                                                           |"),nl,
          write("|                                   MENU                                    |"),nl,
          write("|                                                                           |"),nl,
          write("|     1. AVALIAR FILME                                                      |"),nl,
          write("|     2. VER RECOMENDAÇÕES DO SISTEMA                                       |"),nl,
          write("|     3. CONSULTAR FILME POR ATOR                                           |"),nl,
          write("|     4. CONSULTAR FILME POR DIRETOR                                        |"),nl,
          write("|     5. CONSULTAR FILME POR TITULO                                         |"),nl,
          write("|     6. CONSULTAR FILME POR GENERO                                         |"),nl,
          write("|     7. CONSULTAR LISTA DE DESEJO                                          |"),nl,
          write("|     8. ADICIONAR FILME A LISTA DE DESEJO                                  |"),nl,
          write("|     9. CONSULTAR FILMES ASSISTIDOS                                        |"),nl,
          write("|     0. SAIR DO PROGRAMA                                                   |"),nl,
          write("|                                                                           |"),nl,
          write("|     OPCAO:                                                                |"),nl,
          write("|___________________________________________________________________________|"),nl.
